version: '3'
services:
  generation:
    image: migrate/migrate
    entrypoint: migrate create -ext sql -dir /migrations -seq
    volumes:
      - ./migrations:/migrations
  down:
    image: migrate/migrate
    entrypoint: migrate create -ext sql -dir /migrations -seq
    entrypoint: migrate -path /migrations -database "mysql://user:password@tcp(db:3306)/app" down
    volumes:
      - ./migrations:/migrations
