version: '3'
services:
  db:
    build: ./database
    image: mysql:8.0.22
    restart: always
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./database/conf.d:/etc/mysql/conf.d
      - ./database/initdb.d:/docker-entrypoint-initdb.d
