version: '3'
services:
  db:
    image: mysql:latest
    volumes:
      - ./mysql-confd:/etc/mysql/conf.d
      - ./db_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./src:/myapp
    ports:
      - "3000:3000"
    links:
      - db
